# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘FEGORNUpdate’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FEGORNUpdate
  pod 'AFNetworking',             '~> 3.1.0'
  pod 'ZipArchive',               '~> 1.4.0'
  pod 'React’, :path => ‘../demo/node_modules/react-native’, :subspecs => [
  'Core',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTActionSheet',
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation',
  'RCTLinkingIOS',
  'ART',
  'jschelpers',
  'cxxreact',
  'CxxBridge'
  # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # 如果你的RN版本 >= 0.42.0，则加入下面这行
  pod "yoga", :path => "../demo/node_modules/react-native/ReactCommon/yoga"

  target 'FEGORNUpdateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
